Financial-Times/o-colors

src/scss/_palette.scss

/cc @AlbertoElias @andygnewman 
Following the example of `cold-1` and `cold-2` (which are the same as some of the grey tints) - decided to copy `claret` to `claret-1`.
Bonus is that it allows us to change that color without affecting other apps.

Unification colors

---

demos/palette.html
demos/sass-usage.html
demos/src/config.json
demos/use-cases.html
src/scss/_palette.scss

This is a stable base for the new Next FT designs.
See https://next.ft.com/__styleguide/design-primitives#palette for documentation.
Thanks to @pauloneillft @simonwilliamsFT @adgad and @keirog for their contributions.

Add next colours

---

demos/src/demo.js

Update demo.js with the new build URL due to migrating from Akamai to Fastly.

Change build URLs

---

src/scss/_use-cases.scss

This PR does two things:
1. Next are now using claret in a lot of places, all for a type of utility text called a `tag`. This PR adds this new use-case.
2. Updates the link color from blue to teal, which is the link color next have settled on.

Update for Next

---

src/scss/_palette.scss
src/scss/_use-cases.scss

There are two colors for the tag at the moment. #505050 and n-ui's 'claret-inverse'
I asked Sue Vago about this and she said claret-inverse is the correct color.

Update to tag-hover color

---

src/scss/_palette.scss

Each colour has a darker shade and a lighter shade for hover-states or use on
light backgrounds / dark backgrounds.
b2b is orange
b2c is blue

add b2b and b2c colors

---

origami.json

Allows people to find `o-colors` when searching for the correct spelling of colours.

Add keywords to origami.json

---

src/scss/_palette.scss

Pa11y errors on the contrast of pink-tint-1 with teal. This is a very common color combination and it is very close to not erroring. 
This commit changes the color of pink-tint-1 and its lesser used alias very slightly so these no longer error.
#111

Fix colour contrast of pink tint 1

---

src/scss/_palette.scss

This commit makes a barely perceivable change to teal-1 to make it
meet AA WCAG standards when used at small font sizes:
(left is the new color, right is the old one)

Fix contrast of teal-1 with pink-tint-1 for small sizes

---

migration-guide.md

As far as I can tell there is no `white-50`, so have gone for the nearest one

Fix the “switch to” name for `warm-5` in migration guide

---

src/scss/_palette.scss

Reverts Financial-Times/o-colors#128 – this doesn't pass the contrast checks :( didn't run in the original PR because it was PRed from a fork.
Reverting for now and will fix in a separate PR.

Revert "Fix teal saturation"

---

src/scss/_functions.scss

Use page background.
For the default  "master" brand:
- no change (unless a custom page background has been set)
For the "internal" brand:
- white tints are redundant
- black tints now look like the following
See comment for suggestion to hide the white tints for the internal brand: https://github.com/Financial-Times/o-colors/issues/144

Update the default `oColorsMix` background.

---

src/scss/_use-cases.scss

- Correct internal brand usecases removing "internal-slate".
- Fallback to master brand usecases if the requested brand has no usecases.
- Add whitelabel usecases.
- Removes deprecated internal brand usecases -- hypocritical considering previous feedback recommending the contrary. As there will developers facilitating a move to the internal brand I think we're fine to remove inappropriate usecases.

Update branded usecases.

---

src/scss/_functions.scss
src/scss/_palette.scss
src/scss/_variables.scss

As we are using experimental colours in components now this is spamming clients (e.g. the apps team), even if they are not using the internal brand or experimental colours directly.
Although not ideal, I think we're probably safe to remove the warning so long as the colours are hidden from documentation.

Remove warning as it is spamming clients.

---

src/scss/_functions.scss
test/scss/_functions.test.scss

This fixes a warning that was being caught if a null value was being supplied. 
Seeing as null is ignored by sass, we don't need to catch this.

silence null warnings

---

src/scss/_use-cases.scss
test/scss/_functions.test.scss

Correct the "link-hover" usecase to align to `o-typography`. 
Will follow up with an update to `o-typography` to use this corrected usecase. It's odd because `o-typography` does use the "link" usecase.
https://github.com/Financial-Times/o-typography/blob/b327713245705ce3091cf2f8087733fa23872c6f/src/scss/use-cases/_general.scss#L45
A quick look through visible repositories on Github revealed no reason not to correct this.

Correct the "link-hover" usecase.

---

bower.json

Commits from [here](https://github.com/Financial-Times/o-colors/pull/165) which add a dependancy on `o-brand` where in master but not released.

Correct the brand semver.

---

src/scss/_functions.scss
src/scss/_variables.scss

**Changes** 
- `oColorsGetColorFor` does not warn if common usecases like 'page' are not set.
- `oColorsGetPaletteColor` does not warn when trying to get a color for a `null` usecase.
- Updated Sassdoc return annotation (the return types haven't changed though).
**Why** 
These are common usecase which are not necessarily defined for each brand. When the usecase is used and `null` is returned, there is no need to warn about it. 
E.g. in `o-typography`. There is a warning when calling `color: oColorsGetColorFor('body', 'text');` for the internal brand, but not setting a colour for body copy is desired.
Warning is still useful in other cases to highlight misspelled usecases, or missing custom usecases. 
We might want to solve this in a more robust way in the future, pending the future of …

Do not warn when standard usecases are undefined.

---

demos/src/palettes/whitelabel-palette.json
origami.json

`o-colors` supports the whitelabel implicitly -- make it explicit.

Make whitelabel support explicit.

---

src/scss/_functions.scss
test/scss/_functions.test.scss

Due to an apparent bug in dart-sass we can't use `inspect` with a string to get values from a map.
When compiled by dart-sass: inspect("string") != "string"
https://github.com/sass/dart-sass/issues/594

Support compilation with dart-sass.

---

src/scss/_functions.scss
src/scss/_variables.scss

v4 of o-colors has many palette color deprecations for the internal and whtielabel brands.
These still effect our components, e.g. o-buttons, so users are spammed with warnings they cannot solve. So suppress these warnings until the deprecated colors are removed in the next major.

Silence color palette deprecations for internal/whitelabel brands.

---

src/scss/_functions.scss
src/scss/_palette.scss
src/scss/_variables.scss
test/scss/_master.test.scss

We currently warn that the internal brand colors 'slate-white-15' and 'slate-white-5' are experimental and may be removed at any time. As we use the colours in our own components users can't do anything to prevent the warning, so it's a bit spammy. 
Also, as the colours have been in production for months, in might be considered a little clinical to take them away without a major even though we warn about it. We have a new major of o-colors due anyway, so let's remove those warnings and deprecate like usual when/if we need to.
Until their name and application is cemented within the net major, they're still shown as experimental in the code and in the registry. We're just not going to warn about it or take them away without a major.

Remove experimental internal pallete warnings.

---

demos/src/contrast-checker/contrast-checker.scss
demos/src/shared/contrast-ratio.js

For some reason I haven't managed to figure out, `#808080` (`'black-50'`) defaults to `'gray'` 🤔 and that causes a `NaN` contrast ratio calculation.

fix edge case for contrast calculation

---

src/scss/_functions.scss
test/scss/_functions.test.scss

o-colors outputs a CSS class for each colour in our pallete
to apply the colour as a background, with a foreground of
either black or white. This throws a warning for some combinations
where the contrast is not high enough (wihout 18px typography).
These classes may not be very helpful and should be reconsidered
now CSS Custom Properties are viable for many of our build
service users.
In the meantime we can suppress these default warnings
as they are a nuisance and not useful for Sass users who
are including o-colors with silient mode disabled.

Suppress warnings which are output by default with silient mode off.

---

README.md
main.scss
test/scss/_mixins.test.scss

Add an `oColors` [primary (aka mono) mixin](https://github.com/Financial-Times/origami-proposals/issues/6).
References to silient mode are removed, as primary mixins are
intended to replace silient mode from a users point of view.

Add a primary mixin.

---

README.md
src/scss/_functions.scss
src/scss/_mixins.scss
src/scss/_use-cases.scss
test/scss/_functions.test.scss
test/scss/_mixins.test.scss

We want to [brand o-normalise](https://github.com/Financial-Times/o-normalise/issues/35), making the focus colour differ per brand and [customisable](https://github.com/Financial-Times/o-normalise/issues/40). We already have such logic for sharing branded colours between components in o-colors, so rather than repeat it in o-normalise we can add a usecase in o-colors.
`$o-normalise-focus-color` will be removed in favour of `oColorsGetUseCase(focus, outline)`.
Previously we [backed away](https://github.com/Financial-Times/o-colors/pull/170) from this approach because it was easier to stick with the `o-normalise` variable. There was also some chat about a focus colour not being a state and not a "thing" (read element) which was nonsense from my previous self -- it's a clear usecase for a …

Add focus outline colour.

---

MIGRATION.md
README.md
demos/src/contrast-checker/contrast-checker.scss
demos/src/demo.scss
main.scss
src/scss/_functions.scss
src/scss/_mixins.scss
src/scss/_palette.scss
src/scss/_variables.scss
test/scss/_functions.test.scss
test/scss/_internal.test.scss
test/scss/_master.test.scss
test/scss/_mixins.test.scss
test/scss/_palette.test.scss

- Replace `oColorsGetPaletteColor` with `oColorsGetPalette`.
- Make `$o-colors-palette` private.
- Add function `oColorsGetPalette` to iterate over the palette,
without being able to write to it directly.
- Remove `inherit` and `transparent` from the palette.
- Update `oColorsByName` to support deprecation messages.

Implement oColorsGetPalette and related updates.

---

main.scss
src/scss/_functions.scss
src/scss/_mixins.scss
src/scss/_palette.scss
src/scss/_use-cases.scss
src/scss/_variables.scss

Default usecase and palette colour variables now contain a list of args
for use with mixins. This is simpler than maintaining the structure of
the map used to store set usecases and palette colours manually.

Set default usecase and palette colours consistently.

---

MIGRATION.md
README.md
demos/src/demo.scss
main.scss
src/scss/_functions.scss
src/scss/_mixins.scss
src/scss/_palette.scss
src/scss/_use-cases.scss
src/scss/_variables.scss
test/scss/_mixins.test.scss

**You may want to review just [the first commit](https://github.com/Financial-Times/o-colors/pull/211/commits/3e48989124b7df3275ecd867381ef6125e2e00a0) the latter was merged from [this approved pr](https://github.com/Financial-Times/o-colors/pull/212).**
Updates `oColorsSetUseCase`:
- Adds explicit usecase namespace.
- Adds support for granular usecase property deprecation.
- Errors when setting a usecase which already exists, outside
o-colors defaults which may be overridden.
Updates `oColorsSetColor`:
- Erros when setting a colour which already exists, outside
o-colors defaults which ma be overridden.
Removes variable `$o-colors-branded-usecases`.
Makes demos quiet (hides ignored contrast warnings).

Update `oColorsSetUseCase` and related Sass.

---

MIGRATION.md
src/scss/tools/_color.scss
test/scss/tools/_color.test.scss

The following functions now accept a String of a palette colour name
as well as a Color.
- oColorsColorBrightness
- oColorsColorLuminance
- oColorsGetContrastRatio
`oColorsColorBrightness` also has updated parameters.
See the [v5 proposal](https://github.com/Financial-Times/o-colors/issues/198)
E.g.
```diff
$contrast: oColorsGetContrastRatio(#ffffff, #000000);
-	$contrast: oColorsGetContrastRatio($col1: oColorsGetPaletteColor('paper'), $col2: oColorsGetPaletteColor('teal'));
+	$contrast: oColorsGetContrastRatio($color-a: 'paper', $color-b: 'teal');
```

Update colour utility functions.

---

src/scss/_functions.scss
test/scss/_functions.test.scss

This mixin may be used to get a colour name for a usecase.
It is useful to get a name sometimes, for example to output
more helpful error messages.
This is a sibling of `oColorsByUsecase`, which returns the colour
hex rather than the colour name.

Add `oColorsNameByUsecase`.

---

src/scss/_functions.scss
test/scss/_functions.test.scss

As before try both black and white base colours when generating
a text colour. Continue to prefer white as the base colour
below 65% brightness (as in the current major release).

Fix `oColorsGetTextColor`.

---

src/scss/_functions.scss
src/scss/_mixins.scss
test/scss/_functions.test.scss
test/scss/_mixins.test.scss

As custom colours are namespaced explicitly it was not possible to
create a usecase with a custom colour.
```scss
@include oColorsSetColor(
$project-name: 'o-share',
$color-name: 'super-pink',
$color-hex: #f11050
);
@include oColorsSetUseCase(
$project-name: 'o-share',
$usecase: 'social-icon',
$colors: (
'background': 'super-pink' // nope, super-pink is not in the default palette
)
);
```
This commit updates `oColorsSetUseCase` to support this with a map:
```scss
@include oColorsSetUseCase(
$project-name: 'o-share',
$usecase: 'social-icon',
$colors: (
'background':  ('name': 'super-pink' , 'from': 'o-share')
)
);
```
The api is unchanged for default colours:
```scss
@include oColorsSetUseCase(
$project-name: 'o-share',
$usecase: 'social-icon',
$colors: (
'background':  'teal'
)
);
``` …

Support setting usecases with custom colours.

---

README.md
main.scss
src/scss/_functions.scss
src/scss/_mixins.scss

A colour may be given in a non-hex format.

Remane `$color-hex` arguments to `$color-value`.

---

MIGRATION.md
src/scss/_palette.scss
test/scss/_functions.test.scss

Restore "transparent" to the o-colors palette.

---

src/scss/_functions.scss
test/scss/_functions.test.scss

`$brightness` is used to create the tone, so return `brightness`
instead of `value` with `oColorsGetToneDetails`.

Rename the return value of the tone details function.

---

src/scss/_functions.scss
src/scss/_palette.scss
src/scss/_variables.scss
test/scss/_functions.test.scss

A wheat tone is used in article pages, so allow wheat to be toned
again.

Restore wheat tones.

---

src/scss/_functions.scss
src/scss/_mixins.scss
test/scss/_functions.test.scss
test/scss/_mixins.test.scss

**Allow hex values as colour usecases.**
This enables a usecase to be set to an o-colors mix.
**Remove `oColorsUsecaseDetails`.**
This is only used by the o-buttons beta and is no longer required,
as buttons may now be generated using a hex colour as well as a
colour name. We can remove this.

Usecase hexes

---

src/scss/_mixins.scss
test/scss/_mixins.test.scss

We do not allow custom colours to be overriden. However, components may be
included by a project's dependencies multiple times. This means custom colours
may be set multiple times by the same component. So, only error if a custom
colour is set with a _different_ value.
https://github.com/Financial-Times/o-colors/issues/237

Allow custom colours to be set twice, if the value is unchanged.

---

src/scss/_mixins.scss
test/scss/_mixins.test.scss

Builds on and fixes: 630ef07654045ffe6a05e5a0be47cdc5f2a75337
Relates to: https://github.com/Financial-Times/o-colors/issues/237
Context:
We do not allow custom colour usecases to be overriden. However, components
may be included by a project's dependencies multiple times. This means custom
colours may be set multiple times by the same component. So, only error if a
custom colour is set with a _different_ value.

Allow custom colour usecases to be set twice, if the value is unchanged.

---

demos/src/contrast-checker/fieldsets/mixer.mustache
origami.json

`o-syntax-highlight` does not support the whitelabel brand. It
cannot be included as a dependency to whitelabel brand demos.
Fixes: https://github.com/Financial-Times/o-colors/issues/236

Fix whitelabel demos.

---

origami.json

The Origami spec wants a string. Let's explicitly state we do not have a
description, to distinguish it from when we've forgotten.

Add empty string description to demos without descriptions

---

README.md
demos/src/palettes/internal-palette.json

Mandarin is now used in three different places that we know of:
- SOS for amber rating labels and as a mid-point between green and red
- o-meter
- Biz-Ops (work being done to add an amber label now)
I think we should make it available. I've added it to tertiary colors so
it appears next to jade and crimson, does that make sense?
Resolves #245.

Add Mandarin to the internal brand

---

README.md
demos/src/color-mixer/color-mixer.scss
demos/src/contrast-checker/contrast-checker.scss
origami.json
src/scss/_functions.scss
src/scss/_mixins.scss
src/scss/_palette.scss
src/scss/_variables.scss
test/scss/_functions.test.scss

By default colours do not allow tones to reduce the number of colours
used within a project. To allow tones of custom colours
`oColorsSetColor` has a new option `allow-tones`.
```scss
// Set a custom palette colour within a project `o-example`,
// which allows tones of the same colour.
@include oColorsSetColor(
$color-name: 'o-example/myhotpink',
$color-value: #ff69b4,
$opts: ('allow-tones': true)
);
.example {
// Get a toned custom palette colour from a project `o-example`.
background-color: oColorsGetTone('o-example/myhotpink', 80);
}
```
Our tones work by modifying the brightness value of our palette
colours in the HSB colour space.
The previous major, v4, included a separate function to return a
hex value for given HSB values (hue, saturation, and brightness).
When calculating tones …

Allow custom colour tones

---

demos/src/color-mixer/color-mixer.scss
demos/src/contrast-checker/contrast-checker.scss

These were incorrect due to a bug in origami-build-tools.
https://github.com/Financial-Times/origami-build-tools/pull/734

Correct demo Sass import paths.

---

demos/src/color-mixer/color-mixer.js
demos/src/contrast-checker/contrast-checker.js

relative imports require the full path including the extension because browsers use the import name to make a network request and they do not implicitly add a .js file extension if one is missing

add extension to relative imports to make the code work directly in a browser

---

src/scss/_functions.scss

sass 1.32 deprecated the behaviour of allowing unitless values for saturation and luminence:
>Deprecate passing non-% numbers as lightness and saturation to hsl(), hsla(), color.adjust(), and color.change(). This matches the CSS specification, which also requires % for all lightness and saturation parameters.
> https://github.com/sass/dart-sass/releases/tag/1.32.0
This change makes our saturation and luminence values always be percentages, which is the correct type to use.

ensure the saturation and luminence values are percentages to stop deprecation warnings from being emitted

---

demos/src/palettes/master-palette.json
src/scss/_palette.scss

This is used to indicate partner content (aka paid/promoted content)
Requested by FT Creative, in use in production, ~**awaiting Customer Products design ops approval**~ Josh and Leonardo approve.

Add matisse to the master brand's tertiary palette.

---

demos/src/palettes/master-palette.json
demos/src/partner-content-palette.mustache
origami.json
src/scss/_palette.scss

From FT Creative:
> The new partner content colour ‘Matisse’ is not part of the FT brand colour
> palette - it’s entirely new colour created for Partner Content and
> deliberately different from the FT’s brand colours whilst complementing them.
> Therefore, if you are going to add this to Origami, could I suggest this is
> clearly separate from our Brand secondary/tertiary palette and labelled so in
> the index (similar to eg B2C blues which has its own section)?
The design UI Kit is being updated too

Move matisse under a new "partner content" palette

---

demos/src/contrast-checker/contrast-checker.js
demos/src/shared/colors-mix.js

To verify this locally you will need to modify obt to use compressed css output by changing the default value from `'expanded'` to `'compressed'` -- https://github.com/Financial-Times/origami-build-tools/blob/caddb606d50e7558809d3e79c24182d0d367e3d9/lib/tasks/build-sass.js#L80

Always use a full hex string for the constract checker and colour mixer demos
